// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: urbis.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UrbisService_CreateIndex_FullMethodName       = "/urbis.UrbisService/CreateIndex"
	UrbisService_DestroyIndex_FullMethodName      = "/urbis.UrbisService/DestroyIndex"
	UrbisService_ListIndexes_FullMethodName       = "/urbis.UrbisService/ListIndexes"
	UrbisService_LoadGeoJSON_FullMethodName       = "/urbis.UrbisService/LoadGeoJSON"
	UrbisService_LoadGeoJSONString_FullMethodName = "/urbis.UrbisService/LoadGeoJSONString"
	UrbisService_LoadWKT_FullMethodName           = "/urbis.UrbisService/LoadWKT"
	UrbisService_InsertPoint_FullMethodName       = "/urbis.UrbisService/InsertPoint"
	UrbisService_InsertLineString_FullMethodName  = "/urbis.UrbisService/InsertLineString"
	UrbisService_InsertPolygon_FullMethodName     = "/urbis.UrbisService/InsertPolygon"
	UrbisService_Remove_FullMethodName            = "/urbis.UrbisService/Remove"
	UrbisService_GetObject_FullMethodName         = "/urbis.UrbisService/GetObject"
	UrbisService_Build_FullMethodName             = "/urbis.UrbisService/Build"
	UrbisService_Optimize_FullMethodName          = "/urbis.UrbisService/Optimize"
	UrbisService_QueryRange_FullMethodName        = "/urbis.UrbisService/QueryRange"
	UrbisService_QueryPoint_FullMethodName        = "/urbis.UrbisService/QueryPoint"
	UrbisService_QueryKNN_FullMethodName          = "/urbis.UrbisService/QueryKNN"
	UrbisService_QueryAdjacent_FullMethodName     = "/urbis.UrbisService/QueryAdjacent"
	UrbisService_FindAdjacentPages_FullMethodName = "/urbis.UrbisService/FindAdjacentPages"
	UrbisService_GetStats_FullMethodName          = "/urbis.UrbisService/GetStats"
	UrbisService_GetCount_FullMethodName          = "/urbis.UrbisService/GetCount"
	UrbisService_GetBounds_FullMethodName         = "/urbis.UrbisService/GetBounds"
	UrbisService_Save_FullMethodName              = "/urbis.UrbisService/Save"
	UrbisService_Load_FullMethodName              = "/urbis.UrbisService/Load"
)

// UrbisServiceClient is the client API for UrbisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrbisServiceClient interface {
	// Index Management
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	DestroyIndex(ctx context.Context, in *DestroyIndexRequest, opts ...grpc.CallOption) (*DestroyIndexResponse, error)
	ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error)
	// Data Loading
	LoadGeoJSON(ctx context.Context, in *LoadGeoJSONRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	LoadGeoJSONString(ctx context.Context, in *LoadGeoJSONStringRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	LoadWKT(ctx context.Context, in *LoadWKTRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	// Object Operations
	InsertPoint(ctx context.Context, in *InsertPointRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	InsertLineString(ctx context.Context, in *InsertLineStringRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	InsertPolygon(ctx context.Context, in *InsertPolygonRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	// Index Building
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
	Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	// Spatial Queries
	QueryRange(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryPoint(ctx context.Context, in *PointQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryKNN(ctx context.Context, in *KNNQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryAdjacent(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Disk-Aware Operations
	FindAdjacentPages(ctx context.Context, in *AdjacentPagesRequest, opts ...grpc.CallOption) (*AdjacentPagesResponse, error)
	// Statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	GetCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	GetBounds(ctx context.Context, in *BoundsRequest, opts ...grpc.CallOption) (*BoundsResponse, error)
	// Persistence
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	Load(ctx context.Context, in *LoadIndexRequest, opts ...grpc.CallOption) (*LoadIndexResponse, error)
}

type urbisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrbisServiceClient(cc grpc.ClientConnInterface) UrbisServiceClient {
	return &urbisServiceClient{cc}
}

func (c *urbisServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, UrbisService_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) DestroyIndex(ctx context.Context, in *DestroyIndexRequest, opts ...grpc.CallOption) (*DestroyIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyIndexResponse)
	err := c.cc.Invoke(ctx, UrbisService_DestroyIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndexesResponse)
	err := c.cc.Invoke(ctx, UrbisService_ListIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) LoadGeoJSON(ctx context.Context, in *LoadGeoJSONRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, UrbisService_LoadGeoJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) LoadGeoJSONString(ctx context.Context, in *LoadGeoJSONStringRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, UrbisService_LoadGeoJSONString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) LoadWKT(ctx context.Context, in *LoadWKTRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, UrbisService_LoadWKT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) InsertPoint(ctx context.Context, in *InsertPointRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, UrbisService_InsertPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) InsertLineString(ctx context.Context, in *InsertLineStringRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, UrbisService_InsertLineString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) InsertPolygon(ctx context.Context, in *InsertPolygonRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, UrbisService_InsertPolygon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, UrbisService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, UrbisService_GetObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, UrbisService_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, UrbisService_Optimize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) QueryRange(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, UrbisService_QueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) QueryPoint(ctx context.Context, in *PointQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, UrbisService_QueryPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) QueryKNN(ctx context.Context, in *KNNQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, UrbisService_QueryKNN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) QueryAdjacent(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, UrbisService_QueryAdjacent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) FindAdjacentPages(ctx context.Context, in *AdjacentPagesRequest, opts ...grpc.CallOption) (*AdjacentPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjacentPagesResponse)
	err := c.cc.Invoke(ctx, UrbisService_FindAdjacentPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, UrbisService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) GetCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, UrbisService_GetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) GetBounds(ctx context.Context, in *BoundsRequest, opts ...grpc.CallOption) (*BoundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoundsResponse)
	err := c.cc.Invoke(ctx, UrbisService_GetBounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, UrbisService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urbisServiceClient) Load(ctx context.Context, in *LoadIndexRequest, opts ...grpc.CallOption) (*LoadIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadIndexResponse)
	err := c.cc.Invoke(ctx, UrbisService_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrbisServiceServer is the server API for UrbisService service.
// All implementations must embed UnimplementedUrbisServiceServer
// for forward compatibility.
type UrbisServiceServer interface {
	// Index Management
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	DestroyIndex(context.Context, *DestroyIndexRequest) (*DestroyIndexResponse, error)
	ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error)
	// Data Loading
	LoadGeoJSON(context.Context, *LoadGeoJSONRequest) (*LoadResponse, error)
	LoadGeoJSONString(context.Context, *LoadGeoJSONStringRequest) (*LoadResponse, error)
	LoadWKT(context.Context, *LoadWKTRequest) (*LoadResponse, error)
	// Object Operations
	InsertPoint(context.Context, *InsertPointRequest) (*InsertResponse, error)
	InsertLineString(context.Context, *InsertLineStringRequest) (*InsertResponse, error)
	InsertPolygon(context.Context, *InsertPolygonRequest) (*InsertResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	// Index Building
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	// Spatial Queries
	QueryRange(context.Context, *RangeQueryRequest) (*QueryResponse, error)
	QueryPoint(context.Context, *PointQueryRequest) (*QueryResponse, error)
	QueryKNN(context.Context, *KNNQueryRequest) (*QueryResponse, error)
	QueryAdjacent(context.Context, *RangeQueryRequest) (*QueryResponse, error)
	// Disk-Aware Operations
	FindAdjacentPages(context.Context, *AdjacentPagesRequest) (*AdjacentPagesResponse, error)
	// Statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	GetCount(context.Context, *CountRequest) (*CountResponse, error)
	GetBounds(context.Context, *BoundsRequest) (*BoundsResponse, error)
	// Persistence
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	Load(context.Context, *LoadIndexRequest) (*LoadIndexResponse, error)
	mustEmbedUnimplementedUrbisServiceServer()
}

// UnimplementedUrbisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUrbisServiceServer struct{}

func (UnimplementedUrbisServiceServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedUrbisServiceServer) DestroyIndex(context.Context, *DestroyIndexRequest) (*DestroyIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyIndex not implemented")
}
func (UnimplementedUrbisServiceServer) ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIndexes not implemented")
}
func (UnimplementedUrbisServiceServer) LoadGeoJSON(context.Context, *LoadGeoJSONRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadGeoJSON not implemented")
}
func (UnimplementedUrbisServiceServer) LoadGeoJSONString(context.Context, *LoadGeoJSONStringRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadGeoJSONString not implemented")
}
func (UnimplementedUrbisServiceServer) LoadWKT(context.Context, *LoadWKTRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadWKT not implemented")
}
func (UnimplementedUrbisServiceServer) InsertPoint(context.Context, *InsertPointRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertPoint not implemented")
}
func (UnimplementedUrbisServiceServer) InsertLineString(context.Context, *InsertLineStringRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertLineString not implemented")
}
func (UnimplementedUrbisServiceServer) InsertPolygon(context.Context, *InsertPolygonRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertPolygon not implemented")
}
func (UnimplementedUrbisServiceServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedUrbisServiceServer) GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedUrbisServiceServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedUrbisServiceServer) Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Optimize not implemented")
}
func (UnimplementedUrbisServiceServer) QueryRange(context.Context, *RangeQueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRange not implemented")
}
func (UnimplementedUrbisServiceServer) QueryPoint(context.Context, *PointQueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPoint not implemented")
}
func (UnimplementedUrbisServiceServer) QueryKNN(context.Context, *KNNQueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryKNN not implemented")
}
func (UnimplementedUrbisServiceServer) QueryAdjacent(context.Context, *RangeQueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAdjacent not implemented")
}
func (UnimplementedUrbisServiceServer) FindAdjacentPages(context.Context, *AdjacentPagesRequest) (*AdjacentPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAdjacentPages not implemented")
}
func (UnimplementedUrbisServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedUrbisServiceServer) GetCount(context.Context, *CountRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCount not implemented")
}
func (UnimplementedUrbisServiceServer) GetBounds(context.Context, *BoundsRequest) (*BoundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBounds not implemented")
}
func (UnimplementedUrbisServiceServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedUrbisServiceServer) Load(context.Context, *LoadIndexRequest) (*LoadIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedUrbisServiceServer) mustEmbedUnimplementedUrbisServiceServer() {}
func (UnimplementedUrbisServiceServer) testEmbeddedByValue()                      {}

// UnsafeUrbisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrbisServiceServer will
// result in compilation errors.
type UnsafeUrbisServiceServer interface {
	mustEmbedUnimplementedUrbisServiceServer()
}

func RegisterUrbisServiceServer(s grpc.ServiceRegistrar, srv UrbisServiceServer) {
	// If the following call panics, it indicates UnimplementedUrbisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UrbisService_ServiceDesc, srv)
}

func _UrbisService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_DestroyIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).DestroyIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_DestroyIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).DestroyIndex(ctx, req.(*DestroyIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_ListIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndexesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).ListIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_ListIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).ListIndexes(ctx, req.(*ListIndexesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_LoadGeoJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGeoJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).LoadGeoJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_LoadGeoJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).LoadGeoJSON(ctx, req.(*LoadGeoJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_LoadGeoJSONString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGeoJSONStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).LoadGeoJSONString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_LoadGeoJSONString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).LoadGeoJSONString(ctx, req.(*LoadGeoJSONStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_LoadWKT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadWKTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).LoadWKT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_LoadWKT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).LoadWKT(ctx, req.(*LoadWKTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_InsertPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).InsertPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_InsertPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).InsertPoint(ctx, req.(*InsertPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_InsertLineString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertLineStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).InsertLineString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_InsertLineString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).InsertLineString(ctx, req.(*InsertLineStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_InsertPolygon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPolygonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).InsertPolygon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_InsertPolygon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).InsertPolygon(ctx, req.(*InsertPolygonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_GetObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_Optimize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).Optimize(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_QueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).QueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_QueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).QueryRange(ctx, req.(*RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_QueryPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).QueryPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_QueryPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).QueryPoint(ctx, req.(*PointQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_QueryKNN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KNNQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).QueryKNN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_QueryKNN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).QueryKNN(ctx, req.(*KNNQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_QueryAdjacent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).QueryAdjacent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_QueryAdjacent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).QueryAdjacent(ctx, req.(*RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_FindAdjacentPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjacentPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).FindAdjacentPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_FindAdjacentPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).FindAdjacentPages(ctx, req.(*AdjacentPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_GetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).GetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_GetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).GetCount(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_GetBounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).GetBounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_GetBounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).GetBounds(ctx, req.(*BoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrbisService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrbisServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrbisService_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrbisServiceServer).Load(ctx, req.(*LoadIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrbisService_ServiceDesc is the grpc.ServiceDesc for UrbisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrbisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urbis.UrbisService",
	HandlerType: (*UrbisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _UrbisService_CreateIndex_Handler,
		},
		{
			MethodName: "DestroyIndex",
			Handler:    _UrbisService_DestroyIndex_Handler,
		},
		{
			MethodName: "ListIndexes",
			Handler:    _UrbisService_ListIndexes_Handler,
		},
		{
			MethodName: "LoadGeoJSON",
			Handler:    _UrbisService_LoadGeoJSON_Handler,
		},
		{
			MethodName: "LoadGeoJSONString",
			Handler:    _UrbisService_LoadGeoJSONString_Handler,
		},
		{
			MethodName: "LoadWKT",
			Handler:    _UrbisService_LoadWKT_Handler,
		},
		{
			MethodName: "InsertPoint",
			Handler:    _UrbisService_InsertPoint_Handler,
		},
		{
			MethodName: "InsertLineString",
			Handler:    _UrbisService_InsertLineString_Handler,
		},
		{
			MethodName: "InsertPolygon",
			Handler:    _UrbisService_InsertPolygon_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _UrbisService_Remove_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _UrbisService_GetObject_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _UrbisService_Build_Handler,
		},
		{
			MethodName: "Optimize",
			Handler:    _UrbisService_Optimize_Handler,
		},
		{
			MethodName: "QueryRange",
			Handler:    _UrbisService_QueryRange_Handler,
		},
		{
			MethodName: "QueryPoint",
			Handler:    _UrbisService_QueryPoint_Handler,
		},
		{
			MethodName: "QueryKNN",
			Handler:    _UrbisService_QueryKNN_Handler,
		},
		{
			MethodName: "QueryAdjacent",
			Handler:    _UrbisService_QueryAdjacent_Handler,
		},
		{
			MethodName: "FindAdjacentPages",
			Handler:    _UrbisService_FindAdjacentPages_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _UrbisService_GetStats_Handler,
		},
		{
			MethodName: "GetCount",
			Handler:    _UrbisService_GetCount_Handler,
		},
		{
			MethodName: "GetBounds",
			Handler:    _UrbisService_GetBounds_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _UrbisService_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _UrbisService_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "urbis.proto",
}
