// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: urbis.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Geometry type enumeration
type GeomType int32

const (
	GeomType_GEOM_POINT      GeomType = 0
	GeomType_GEOM_LINESTRING GeomType = 1
	GeomType_GEOM_POLYGON    GeomType = 2
)

// Enum value maps for GeomType.
var (
	GeomType_name = map[int32]string{
		0: "GEOM_POINT",
		1: "GEOM_LINESTRING",
		2: "GEOM_POLYGON",
	}
	GeomType_value = map[string]int32{
		"GEOM_POINT":      0,
		"GEOM_LINESTRING": 1,
		"GEOM_POLYGON":    2,
	}
)

func (x GeomType) Enum() *GeomType {
	p := new(GeomType)
	*p = x
	return p
}

func (x GeomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeomType) Descriptor() protoreflect.EnumDescriptor {
	return file_urbis_proto_enumTypes[0].Descriptor()
}

func (GeomType) Type() protoreflect.EnumType {
	return &file_urbis_proto_enumTypes[0]
}

func (x GeomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeomType.Descriptor instead.
func (GeomType) EnumDescriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{0}
}

// 2D Point
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_urbis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Minimum Bounding Rectangle (axis-aligned bounding box)
type MBR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinX          float64                `protobuf:"fixed64,1,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MinY          float64                `protobuf:"fixed64,2,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxX          float64                `protobuf:"fixed64,3,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MaxY          float64                `protobuf:"fixed64,4,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MBR) Reset() {
	*x = MBR{}
	mi := &file_urbis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MBR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MBR) ProtoMessage() {}

func (x *MBR) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MBR.ProtoReflect.Descriptor instead.
func (*MBR) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{1}
}

func (x *MBR) GetMinX() float64 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *MBR) GetMinY() float64 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *MBR) GetMaxX() float64 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *MBR) GetMaxY() float64 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

// LineString - sequence of connected points
type LineString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineString) Reset() {
	*x = LineString{}
	mi := &file_urbis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineString) ProtoMessage() {}

func (x *LineString) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineString.ProtoReflect.Descriptor instead.
func (*LineString) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{2}
}

func (x *LineString) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

// Polygon with exterior ring and optional holes
type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exterior      []*Point               `protobuf:"bytes,1,rep,name=exterior,proto3" json:"exterior,omitempty"`
	Holes         []*Ring                `protobuf:"bytes,2,rep,name=holes,proto3" json:"holes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_urbis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{3}
}

func (x *Polygon) GetExterior() []*Point {
	if x != nil {
		return x.Exterior
	}
	return nil
}

func (x *Polygon) GetHoles() []*Ring {
	if x != nil {
		return x.Holes
	}
	return nil
}

// Ring (used for polygon holes)
type Ring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ring) Reset() {
	*x = Ring{}
	mi := &file_urbis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ring) ProtoMessage() {}

func (x *Ring) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ring.ProtoReflect.Descriptor instead.
func (*Ring) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{4}
}

func (x *Ring) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

// Spatial object containing geometry and metadata
type SpatialObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  GeomType               `protobuf:"varint,2,opt,name=type,proto3,enum=urbis.GeomType" json:"type,omitempty"`
	// Types that are valid to be assigned to Geometry:
	//
	//	*SpatialObject_Point
	//	*SpatialObject_Line
	//	*SpatialObject_Polygon
	Geometry      isSpatialObject_Geometry `protobuf_oneof:"geometry"`
	Centroid      *Point                   `protobuf:"bytes,6,opt,name=centroid,proto3" json:"centroid,omitempty"`
	Mbr           *MBR                     `protobuf:"bytes,7,opt,name=mbr,proto3" json:"mbr,omitempty"`
	Properties    []byte                   `protobuf:"bytes,8,opt,name=properties,proto3" json:"properties,omitempty"` // JSON encoded properties
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpatialObject) Reset() {
	*x = SpatialObject{}
	mi := &file_urbis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpatialObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatialObject) ProtoMessage() {}

func (x *SpatialObject) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatialObject.ProtoReflect.Descriptor instead.
func (*SpatialObject) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{5}
}

func (x *SpatialObject) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpatialObject) GetType() GeomType {
	if x != nil {
		return x.Type
	}
	return GeomType_GEOM_POINT
}

func (x *SpatialObject) GetGeometry() isSpatialObject_Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *SpatialObject) GetPoint() *Point {
	if x != nil {
		if x, ok := x.Geometry.(*SpatialObject_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *SpatialObject) GetLine() *LineString {
	if x != nil {
		if x, ok := x.Geometry.(*SpatialObject_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *SpatialObject) GetPolygon() *Polygon {
	if x != nil {
		if x, ok := x.Geometry.(*SpatialObject_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

func (x *SpatialObject) GetCentroid() *Point {
	if x != nil {
		return x.Centroid
	}
	return nil
}

func (x *SpatialObject) GetMbr() *MBR {
	if x != nil {
		return x.Mbr
	}
	return nil
}

func (x *SpatialObject) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

type isSpatialObject_Geometry interface {
	isSpatialObject_Geometry()
}

type SpatialObject_Point struct {
	Point *Point `protobuf:"bytes,3,opt,name=point,proto3,oneof"`
}

type SpatialObject_Line struct {
	Line *LineString `protobuf:"bytes,4,opt,name=line,proto3,oneof"`
}

type SpatialObject_Polygon struct {
	Polygon *Polygon `protobuf:"bytes,5,opt,name=polygon,proto3,oneof"`
}

func (*SpatialObject_Point) isSpatialObject_Geometry() {}

func (*SpatialObject_Line) isSpatialObject_Geometry() {}

func (*SpatialObject_Polygon) isSpatialObject_Geometry() {}

type Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockSize      uint64                 `protobuf:"varint,1,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`                // Max objects per block (default: 1024)
	PageCapacity   uint64                 `protobuf:"varint,2,opt,name=page_capacity,json=pageCapacity,proto3" json:"page_capacity,omitempty"`       // Max objects per page (default: 64)
	CacheSize      uint64                 `protobuf:"varint,3,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`                // Page cache size (default: 128)
	EnableQuadtree bool                   `protobuf:"varint,4,opt,name=enable_quadtree,json=enableQuadtree,proto3" json:"enable_quadtree,omitempty"` // Enable quadtree for adjacency (default: true)
	Persist        bool                   `protobuf:"varint,5,opt,name=persist,proto3" json:"persist,omitempty"`                                     // Enable persistence (default: false)
	DataPath       string                 `protobuf:"bytes,6,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"`                    // Path for data file (if persist=true)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_urbis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{6}
}

func (x *Config) GetBlockSize() uint64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *Config) GetPageCapacity() uint64 {
	if x != nil {
		return x.PageCapacity
	}
	return 0
}

func (x *Config) GetCacheSize() uint64 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *Config) GetEnableQuadtree() bool {
	if x != nil {
		return x.EnableQuadtree
	}
	return false
}

func (x *Config) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *Config) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

type Stats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalObjects      uint64                 `protobuf:"varint,1,opt,name=total_objects,json=totalObjects,proto3" json:"total_objects,omitempty"`
	TotalBlocks       uint64                 `protobuf:"varint,2,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	TotalPages        uint64                 `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalTracks       uint64                 `protobuf:"varint,4,opt,name=total_tracks,json=totalTracks,proto3" json:"total_tracks,omitempty"`
	AvgObjectsPerPage float64                `protobuf:"fixed64,5,opt,name=avg_objects_per_page,json=avgObjectsPerPage,proto3" json:"avg_objects_per_page,omitempty"`
	PageUtilization   float64                `protobuf:"fixed64,6,opt,name=page_utilization,json=pageUtilization,proto3" json:"page_utilization,omitempty"`
	KdtreeDepth       uint64                 `protobuf:"varint,7,opt,name=kdtree_depth,json=kdtreeDepth,proto3" json:"kdtree_depth,omitempty"`
	QuadtreeDepth     uint64                 `protobuf:"varint,8,opt,name=quadtree_depth,json=quadtreeDepth,proto3" json:"quadtree_depth,omitempty"`
	Bounds            *MBR                   `protobuf:"bytes,9,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_urbis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{7}
}

func (x *Stats) GetTotalObjects() uint64 {
	if x != nil {
		return x.TotalObjects
	}
	return 0
}

func (x *Stats) GetTotalBlocks() uint64 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *Stats) GetTotalPages() uint64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Stats) GetTotalTracks() uint64 {
	if x != nil {
		return x.TotalTracks
	}
	return 0
}

func (x *Stats) GetAvgObjectsPerPage() float64 {
	if x != nil {
		return x.AvgObjectsPerPage
	}
	return 0
}

func (x *Stats) GetPageUtilization() float64 {
	if x != nil {
		return x.PageUtilization
	}
	return 0
}

func (x *Stats) GetKdtreeDepth() uint64 {
	if x != nil {
		return x.KdtreeDepth
	}
	return 0
}

func (x *Stats) GetQuadtreeDepth() uint64 {
	if x != nil {
		return x.QuadtreeDepth
	}
	return 0
}

func (x *Stats) GetBounds() *MBR {
	if x != nil {
		return x.Bounds
	}
	return nil
}

// Page information for disk-aware queries
type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        uint32                 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	TrackId       uint32                 `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_urbis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{8}
}

func (x *PageInfo) GetPageId() uint32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *PageInfo) GetTrackId() uint32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type CreateIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"` // Client-provided index identifier
	Config        *Config                `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`                  // Optional configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_urbis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{9}
}

func (x *CreateIndexRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *CreateIndexRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_urbis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{10}
}

func (x *CreateIndexResponse) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *CreateIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestroyIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyIndexRequest) Reset() {
	*x = DestroyIndexRequest{}
	mi := &file_urbis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyIndexRequest) ProtoMessage() {}

func (x *DestroyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyIndexRequest.ProtoReflect.Descriptor instead.
func (*DestroyIndexRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyIndexRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type DestroyIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyIndexResponse) Reset() {
	*x = DestroyIndexResponse{}
	mi := &file_urbis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyIndexResponse) ProtoMessage() {}

func (x *DestroyIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyIndexResponse.ProtoReflect.Descriptor instead.
func (*DestroyIndexResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{12}
}

func (x *DestroyIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListIndexesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesRequest) Reset() {
	*x = ListIndexesRequest{}
	mi := &file_urbis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesRequest) ProtoMessage() {}

func (x *ListIndexesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{13}
}

type ListIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexIds      []string               `protobuf:"bytes,1,rep,name=index_ids,json=indexIds,proto3" json:"index_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesResponse) Reset() {
	*x = ListIndexesResponse{}
	mi := &file_urbis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesResponse) ProtoMessage() {}

func (x *ListIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{14}
}

func (x *ListIndexesResponse) GetIndexIds() []string {
	if x != nil {
		return x.IndexIds
	}
	return nil
}

type LoadGeoJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // File path to GeoJSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGeoJSONRequest) Reset() {
	*x = LoadGeoJSONRequest{}
	mi := &file_urbis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGeoJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGeoJSONRequest) ProtoMessage() {}

func (x *LoadGeoJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGeoJSONRequest.ProtoReflect.Descriptor instead.
func (*LoadGeoJSONRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{15}
}

func (x *LoadGeoJSONRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *LoadGeoJSONRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LoadGeoJSONStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Geojson       string                 `protobuf:"bytes,2,opt,name=geojson,proto3" json:"geojson,omitempty"` // GeoJSON content as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGeoJSONStringRequest) Reset() {
	*x = LoadGeoJSONStringRequest{}
	mi := &file_urbis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGeoJSONStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGeoJSONStringRequest) ProtoMessage() {}

func (x *LoadGeoJSONStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGeoJSONStringRequest.ProtoReflect.Descriptor instead.
func (*LoadGeoJSONStringRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{16}
}

func (x *LoadGeoJSONStringRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *LoadGeoJSONStringRequest) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

type LoadWKTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Wkt           string                 `protobuf:"bytes,2,opt,name=wkt,proto3" json:"wkt,omitempty"` // WKT geometry string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadWKTRequest) Reset() {
	*x = LoadWKTRequest{}
	mi := &file_urbis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadWKTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadWKTRequest) ProtoMessage() {}

func (x *LoadWKTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadWKTRequest.ProtoReflect.Descriptor instead.
func (*LoadWKTRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{17}
}

func (x *LoadWKTRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *LoadWKTRequest) GetWkt() string {
	if x != nil {
		return x.Wkt
	}
	return ""
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectsLoaded uint64                 `protobuf:"varint,1,opt,name=objects_loaded,json=objectsLoaded,proto3" json:"objects_loaded,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_urbis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{18}
}

func (x *LoadResponse) GetObjectsLoaded() uint64 {
	if x != nil {
		return x.ObjectsLoaded
	}
	return 0
}

func (x *LoadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InsertPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPointRequest) Reset() {
	*x = InsertPointRequest{}
	mi := &file_urbis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPointRequest) ProtoMessage() {}

func (x *InsertPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPointRequest.ProtoReflect.Descriptor instead.
func (*InsertPointRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{19}
}

func (x *InsertPointRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *InsertPointRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *InsertPointRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type InsertLineStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Points        []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertLineStringRequest) Reset() {
	*x = InsertLineStringRequest{}
	mi := &file_urbis_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertLineStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLineStringRequest) ProtoMessage() {}

func (x *InsertLineStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLineStringRequest.ProtoReflect.Descriptor instead.
func (*InsertLineStringRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{20}
}

func (x *InsertLineStringRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *InsertLineStringRequest) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type InsertPolygonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Exterior      []*Point               `protobuf:"bytes,2,rep,name=exterior,proto3" json:"exterior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPolygonRequest) Reset() {
	*x = InsertPolygonRequest{}
	mi := &file_urbis_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPolygonRequest) ProtoMessage() {}

func (x *InsertPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPolygonRequest.ProtoReflect.Descriptor instead.
func (*InsertPolygonRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{21}
}

func (x *InsertPolygonRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *InsertPolygonRequest) GetExterior() []*Point {
	if x != nil {
		return x.Exterior
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_urbis_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{22}
}

func (x *InsertResponse) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	ObjectId      uint64                 `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_urbis_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *RemoveRequest) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_urbis_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	ObjectId      uint64                 `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_urbis_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{25}
}

func (x *GetObjectRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *GetObjectRequest) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *SpatialObject         `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_urbis_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{26}
}

func (x *GetObjectResponse) GetObject() *SpatialObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GetObjectResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_urbis_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{27}
}

func (x *BuildRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	BuildTimeMs   float64                `protobuf:"fixed64,2,opt,name=build_time_ms,json=buildTimeMs,proto3" json:"build_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_urbis_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{28}
}

func (x *BuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildResponse) GetBuildTimeMs() float64 {
	if x != nil {
		return x.BuildTimeMs
	}
	return 0
}

type OptimizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_urbis_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{29}
}

func (x *OptimizeRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type OptimizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_urbis_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{30}
}

func (x *OptimizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RangeQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Range         *MBR                   `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeQueryRequest) Reset() {
	*x = RangeQueryRequest{}
	mi := &file_urbis_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeQueryRequest) ProtoMessage() {}

func (x *RangeQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeQueryRequest.ProtoReflect.Descriptor instead.
func (*RangeQueryRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{31}
}

func (x *RangeQueryRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *RangeQueryRequest) GetRange() *MBR {
	if x != nil {
		return x.Range
	}
	return nil
}

type PointQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointQueryRequest) Reset() {
	*x = PointQueryRequest{}
	mi := &file_urbis_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointQueryRequest) ProtoMessage() {}

func (x *PointQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointQueryRequest.ProtoReflect.Descriptor instead.
func (*PointQueryRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{32}
}

func (x *PointQueryRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *PointQueryRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PointQueryRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type KNNQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	K             uint32                 `protobuf:"varint,4,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KNNQueryRequest) Reset() {
	*x = KNNQueryRequest{}
	mi := &file_urbis_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KNNQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KNNQueryRequest) ProtoMessage() {}

func (x *KNNQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KNNQueryRequest.ProtoReflect.Descriptor instead.
func (*KNNQueryRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{33}
}

func (x *KNNQueryRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *KNNQueryRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *KNNQueryRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *KNNQueryRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*SpatialObject       `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	QueryTimeMs   float64                `protobuf:"fixed64,3,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_urbis_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{34}
}

func (x *QueryResponse) GetObjects() []*SpatialObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *QueryResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueryResponse) GetQueryTimeMs() float64 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type AdjacentPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Region        *MBR                   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjacentPagesRequest) Reset() {
	*x = AdjacentPagesRequest{}
	mi := &file_urbis_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjacentPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjacentPagesRequest) ProtoMessage() {}

func (x *AdjacentPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjacentPagesRequest.ProtoReflect.Descriptor instead.
func (*AdjacentPagesRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{35}
}

func (x *AdjacentPagesRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *AdjacentPagesRequest) GetRegion() *MBR {
	if x != nil {
		return x.Region
	}
	return nil
}

type AdjacentPagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pages          []*PageInfo            `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	Count          uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	EstimatedSeeks uint64                 `protobuf:"varint,3,opt,name=estimated_seeks,json=estimatedSeeks,proto3" json:"estimated_seeks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdjacentPagesResponse) Reset() {
	*x = AdjacentPagesResponse{}
	mi := &file_urbis_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjacentPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjacentPagesResponse) ProtoMessage() {}

func (x *AdjacentPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjacentPagesResponse.ProtoReflect.Descriptor instead.
func (*AdjacentPagesResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{36}
}

func (x *AdjacentPagesResponse) GetPages() []*PageInfo {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *AdjacentPagesResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AdjacentPagesResponse) GetEstimatedSeeks() uint64 {
	if x != nil {
		return x.EstimatedSeeks
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_urbis_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{37}
}

func (x *StatsRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_urbis_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{38}
}

func (x *StatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_urbis_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{39}
}

func (x *CountRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_urbis_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{40}
}

func (x *CountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BoundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundsRequest) Reset() {
	*x = BoundsRequest{}
	mi := &file_urbis_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundsRequest) ProtoMessage() {}

func (x *BoundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundsRequest.ProtoReflect.Descriptor instead.
func (*BoundsRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{41}
}

func (x *BoundsRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type BoundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounds        *MBR                   `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundsResponse) Reset() {
	*x = BoundsResponse{}
	mi := &file_urbis_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundsResponse) ProtoMessage() {}

func (x *BoundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundsResponse.ProtoReflect.Descriptor instead.
func (*BoundsResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{42}
}

func (x *BoundsResponse) GetBounds() *MBR {
	if x != nil {
		return x.Bounds
	}
	return nil
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_urbis_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{43}
}

func (x *SaveRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *SaveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_urbis_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{44}
}

func (x *SaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoadIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIndexRequest) Reset() {
	*x = LoadIndexRequest{}
	mi := &file_urbis_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIndexRequest) ProtoMessage() {}

func (x *LoadIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIndexRequest.ProtoReflect.Descriptor instead.
func (*LoadIndexRequest) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{45}
}

func (x *LoadIndexRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *LoadIndexRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LoadIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIndexResponse) Reset() {
	*x = LoadIndexResponse{}
	mi := &file_urbis_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIndexResponse) ProtoMessage() {}

func (x *LoadIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urbis_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIndexResponse.ProtoReflect.Descriptor instead.
func (*LoadIndexResponse) Descriptor() ([]byte, []int) {
	return file_urbis_proto_rawDescGZIP(), []int{46}
}

func (x *LoadIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_urbis_proto protoreflect.FileDescriptor

const file_urbis_proto_rawDesc = "" +
	"\n" +
	"\vurbis.proto\x12\x05urbis\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"Y\n" +
	"\x03MBR\x12\x13\n" +
	"\x05min_x\x18\x01 \x01(\x01R\x04minX\x12\x13\n" +
	"\x05min_y\x18\x02 \x01(\x01R\x04minY\x12\x13\n" +
	"\x05max_x\x18\x03 \x01(\x01R\x04maxX\x12\x13\n" +
	"\x05max_y\x18\x04 \x01(\x01R\x04maxY\"2\n" +
	"\n" +
	"LineString\x12$\n" +
	"\x06points\x18\x01 \x03(\v2\f.urbis.PointR\x06points\"V\n" +
	"\aPolygon\x12(\n" +
	"\bexterior\x18\x01 \x03(\v2\f.urbis.PointR\bexterior\x12!\n" +
	"\x05holes\x18\x02 \x03(\v2\v.urbis.RingR\x05holes\",\n" +
	"\x04Ring\x12$\n" +
	"\x06points\x18\x01 \x03(\v2\f.urbis.PointR\x06points\"\xb3\x02\n" +
	"\rSpatialObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.urbis.GeomTypeR\x04type\x12$\n" +
	"\x05point\x18\x03 \x01(\v2\f.urbis.PointH\x00R\x05point\x12'\n" +
	"\x04line\x18\x04 \x01(\v2\x11.urbis.LineStringH\x00R\x04line\x12*\n" +
	"\apolygon\x18\x05 \x01(\v2\x0e.urbis.PolygonH\x00R\apolygon\x12(\n" +
	"\bcentroid\x18\x06 \x01(\v2\f.urbis.PointR\bcentroid\x12\x1c\n" +
	"\x03mbr\x18\a \x01(\v2\n" +
	".urbis.MBRR\x03mbr\x12\x1e\n" +
	"\n" +
	"properties\x18\b \x01(\fR\n" +
	"propertiesB\n" +
	"\n" +
	"\bgeometry\"\xcb\x01\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"block_size\x18\x01 \x01(\x04R\tblockSize\x12#\n" +
	"\rpage_capacity\x18\x02 \x01(\x04R\fpageCapacity\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x03 \x01(\x04R\tcacheSize\x12'\n" +
	"\x0fenable_quadtree\x18\x04 \x01(\bR\x0eenableQuadtree\x12\x18\n" +
	"\apersist\x18\x05 \x01(\bR\apersist\x12\x1b\n" +
	"\tdata_path\x18\x06 \x01(\tR\bdataPath\"\xdd\x02\n" +
	"\x05Stats\x12#\n" +
	"\rtotal_objects\x18\x01 \x01(\x04R\ftotalObjects\x12!\n" +
	"\ftotal_blocks\x18\x02 \x01(\x04R\vtotalBlocks\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x04R\n" +
	"totalPages\x12!\n" +
	"\ftotal_tracks\x18\x04 \x01(\x04R\vtotalTracks\x12/\n" +
	"\x14avg_objects_per_page\x18\x05 \x01(\x01R\x11avgObjectsPerPage\x12)\n" +
	"\x10page_utilization\x18\x06 \x01(\x01R\x0fpageUtilization\x12!\n" +
	"\fkdtree_depth\x18\a \x01(\x04R\vkdtreeDepth\x12%\n" +
	"\x0equadtree_depth\x18\b \x01(\x04R\rquadtreeDepth\x12\"\n" +
	"\x06bounds\x18\t \x01(\v2\n" +
	".urbis.MBRR\x06bounds\">\n" +
	"\bPageInfo\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\rR\x06pageId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\rR\atrackId\"V\n" +
	"\x12CreateIndexRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12%\n" +
	"\x06config\x18\x02 \x01(\v2\r.urbis.ConfigR\x06config\"J\n" +
	"\x13CreateIndexResponse\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x13DestroyIndexRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\"0\n" +
	"\x14DestroyIndexResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x14\n" +
	"\x12ListIndexesRequest\"2\n" +
	"\x13ListIndexesResponse\x12\x1b\n" +
	"\tindex_ids\x18\x01 \x03(\tR\bindexIds\"C\n" +
	"\x12LoadGeoJSONRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"O\n" +
	"\x18LoadGeoJSONStringRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x18\n" +
	"\ageojson\x18\x02 \x01(\tR\ageojson\"=\n" +
	"\x0eLoadWKTRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x10\n" +
	"\x03wkt\x18\x02 \x01(\tR\x03wkt\"O\n" +
	"\fLoadResponse\x12%\n" +
	"\x0eobjects_loaded\x18\x01 \x01(\x04R\robjectsLoaded\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x12InsertPointRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\"Z\n" +
	"\x17InsertLineStringRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12$\n" +
	"\x06points\x18\x02 \x03(\v2\f.urbis.PointR\x06points\"[\n" +
	"\x14InsertPolygonRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12(\n" +
	"\bexterior\x18\x02 \x03(\v2\f.urbis.PointR\bexterior\"-\n" +
	"\x0eInsertResponse\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\"G\n" +
	"\rRemoveRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x04R\bobjectId\"*\n" +
	"\x0eRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x10GetObjectRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x04R\bobjectId\"W\n" +
	"\x11GetObjectResponse\x12,\n" +
	"\x06object\x18\x01 \x01(\v2\x14.urbis.SpatialObjectR\x06object\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\")\n" +
	"\fBuildRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\"M\n" +
	"\rBuildResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\"\n" +
	"\rbuild_time_ms\x18\x02 \x01(\x01R\vbuildTimeMs\",\n" +
	"\x0fOptimizeRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\",\n" +
	"\x10OptimizeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"P\n" +
	"\x11RangeQueryRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12 \n" +
	"\x05range\x18\x02 \x01(\v2\n" +
	".urbis.MBRR\x05range\"J\n" +
	"\x11PointQueryRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\"V\n" +
	"\x0fKNNQueryRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01k\x18\x04 \x01(\rR\x01k\"y\n" +
	"\rQueryResponse\x12.\n" +
	"\aobjects\x18\x01 \x03(\v2\x14.urbis.SpatialObjectR\aobjects\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\"\n" +
	"\rquery_time_ms\x18\x03 \x01(\x01R\vqueryTimeMs\"U\n" +
	"\x14AdjacentPagesRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\"\n" +
	"\x06region\x18\x02 \x01(\v2\n" +
	".urbis.MBRR\x06region\"}\n" +
	"\x15AdjacentPagesResponse\x12%\n" +
	"\x05pages\x18\x01 \x03(\v2\x0f.urbis.PageInfoR\x05pages\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12'\n" +
	"\x0festimated_seeks\x18\x03 \x01(\x04R\x0eestimatedSeeks\")\n" +
	"\fStatsRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\"3\n" +
	"\rStatsResponse\x12\"\n" +
	"\x05stats\x18\x01 \x01(\v2\f.urbis.StatsR\x05stats\")\n" +
	"\fCountRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"*\n" +
	"\rBoundsRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\"4\n" +
	"\x0eBoundsResponse\x12\"\n" +
	"\x06bounds\x18\x01 \x01(\v2\n" +
	".urbis.MBRR\x06bounds\"<\n" +
	"\vSaveRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"(\n" +
	"\fSaveResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"A\n" +
	"\x10LoadIndexRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"-\n" +
	"\x11LoadIndexResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*A\n" +
	"\bGeomType\x12\x0e\n" +
	"\n" +
	"GEOM_POINT\x10\x00\x12\x13\n" +
	"\x0fGEOM_LINESTRING\x10\x01\x12\x10\n" +
	"\fGEOM_POLYGON\x10\x022\xb8\v\n" +
	"\fUrbisService\x12D\n" +
	"\vCreateIndex\x12\x19.urbis.CreateIndexRequest\x1a\x1a.urbis.CreateIndexResponse\x12G\n" +
	"\fDestroyIndex\x12\x1a.urbis.DestroyIndexRequest\x1a\x1b.urbis.DestroyIndexResponse\x12D\n" +
	"\vListIndexes\x12\x19.urbis.ListIndexesRequest\x1a\x1a.urbis.ListIndexesResponse\x12=\n" +
	"\vLoadGeoJSON\x12\x19.urbis.LoadGeoJSONRequest\x1a\x13.urbis.LoadResponse\x12I\n" +
	"\x11LoadGeoJSONString\x12\x1f.urbis.LoadGeoJSONStringRequest\x1a\x13.urbis.LoadResponse\x125\n" +
	"\aLoadWKT\x12\x15.urbis.LoadWKTRequest\x1a\x13.urbis.LoadResponse\x12?\n" +
	"\vInsertPoint\x12\x19.urbis.InsertPointRequest\x1a\x15.urbis.InsertResponse\x12I\n" +
	"\x10InsertLineString\x12\x1e.urbis.InsertLineStringRequest\x1a\x15.urbis.InsertResponse\x12C\n" +
	"\rInsertPolygon\x12\x1b.urbis.InsertPolygonRequest\x1a\x15.urbis.InsertResponse\x125\n" +
	"\x06Remove\x12\x14.urbis.RemoveRequest\x1a\x15.urbis.RemoveResponse\x12>\n" +
	"\tGetObject\x12\x17.urbis.GetObjectRequest\x1a\x18.urbis.GetObjectResponse\x122\n" +
	"\x05Build\x12\x13.urbis.BuildRequest\x1a\x14.urbis.BuildResponse\x12;\n" +
	"\bOptimize\x12\x16.urbis.OptimizeRequest\x1a\x17.urbis.OptimizeResponse\x12<\n" +
	"\n" +
	"QueryRange\x12\x18.urbis.RangeQueryRequest\x1a\x14.urbis.QueryResponse\x12<\n" +
	"\n" +
	"QueryPoint\x12\x18.urbis.PointQueryRequest\x1a\x14.urbis.QueryResponse\x128\n" +
	"\bQueryKNN\x12\x16.urbis.KNNQueryRequest\x1a\x14.urbis.QueryResponse\x12?\n" +
	"\rQueryAdjacent\x12\x18.urbis.RangeQueryRequest\x1a\x14.urbis.QueryResponse\x12N\n" +
	"\x11FindAdjacentPages\x12\x1b.urbis.AdjacentPagesRequest\x1a\x1c.urbis.AdjacentPagesResponse\x125\n" +
	"\bGetStats\x12\x13.urbis.StatsRequest\x1a\x14.urbis.StatsResponse\x125\n" +
	"\bGetCount\x12\x13.urbis.CountRequest\x1a\x14.urbis.CountResponse\x128\n" +
	"\tGetBounds\x12\x14.urbis.BoundsRequest\x1a\x15.urbis.BoundsResponse\x12/\n" +
	"\x04Save\x12\x12.urbis.SaveRequest\x1a\x13.urbis.SaveResponse\x129\n" +
	"\x04Load\x12\x17.urbis.LoadIndexRequest\x1a\x18.urbis.LoadIndexResponseB\x1dZ\x1bgithub.com/urbis/api/pkg/pbb\x06proto3"

var (
	file_urbis_proto_rawDescOnce sync.Once
	file_urbis_proto_rawDescData []byte
)

func file_urbis_proto_rawDescGZIP() []byte {
	file_urbis_proto_rawDescOnce.Do(func() {
		file_urbis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urbis_proto_rawDesc), len(file_urbis_proto_rawDesc)))
	})
	return file_urbis_proto_rawDescData
}

var file_urbis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_urbis_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_urbis_proto_goTypes = []any{
	(GeomType)(0),                    // 0: urbis.GeomType
	(*Point)(nil),                    // 1: urbis.Point
	(*MBR)(nil),                      // 2: urbis.MBR
	(*LineString)(nil),               // 3: urbis.LineString
	(*Polygon)(nil),                  // 4: urbis.Polygon
	(*Ring)(nil),                     // 5: urbis.Ring
	(*SpatialObject)(nil),            // 6: urbis.SpatialObject
	(*Config)(nil),                   // 7: urbis.Config
	(*Stats)(nil),                    // 8: urbis.Stats
	(*PageInfo)(nil),                 // 9: urbis.PageInfo
	(*CreateIndexRequest)(nil),       // 10: urbis.CreateIndexRequest
	(*CreateIndexResponse)(nil),      // 11: urbis.CreateIndexResponse
	(*DestroyIndexRequest)(nil),      // 12: urbis.DestroyIndexRequest
	(*DestroyIndexResponse)(nil),     // 13: urbis.DestroyIndexResponse
	(*ListIndexesRequest)(nil),       // 14: urbis.ListIndexesRequest
	(*ListIndexesResponse)(nil),      // 15: urbis.ListIndexesResponse
	(*LoadGeoJSONRequest)(nil),       // 16: urbis.LoadGeoJSONRequest
	(*LoadGeoJSONStringRequest)(nil), // 17: urbis.LoadGeoJSONStringRequest
	(*LoadWKTRequest)(nil),           // 18: urbis.LoadWKTRequest
	(*LoadResponse)(nil),             // 19: urbis.LoadResponse
	(*InsertPointRequest)(nil),       // 20: urbis.InsertPointRequest
	(*InsertLineStringRequest)(nil),  // 21: urbis.InsertLineStringRequest
	(*InsertPolygonRequest)(nil),     // 22: urbis.InsertPolygonRequest
	(*InsertResponse)(nil),           // 23: urbis.InsertResponse
	(*RemoveRequest)(nil),            // 24: urbis.RemoveRequest
	(*RemoveResponse)(nil),           // 25: urbis.RemoveResponse
	(*GetObjectRequest)(nil),         // 26: urbis.GetObjectRequest
	(*GetObjectResponse)(nil),        // 27: urbis.GetObjectResponse
	(*BuildRequest)(nil),             // 28: urbis.BuildRequest
	(*BuildResponse)(nil),            // 29: urbis.BuildResponse
	(*OptimizeRequest)(nil),          // 30: urbis.OptimizeRequest
	(*OptimizeResponse)(nil),         // 31: urbis.OptimizeResponse
	(*RangeQueryRequest)(nil),        // 32: urbis.RangeQueryRequest
	(*PointQueryRequest)(nil),        // 33: urbis.PointQueryRequest
	(*KNNQueryRequest)(nil),          // 34: urbis.KNNQueryRequest
	(*QueryResponse)(nil),            // 35: urbis.QueryResponse
	(*AdjacentPagesRequest)(nil),     // 36: urbis.AdjacentPagesRequest
	(*AdjacentPagesResponse)(nil),    // 37: urbis.AdjacentPagesResponse
	(*StatsRequest)(nil),             // 38: urbis.StatsRequest
	(*StatsResponse)(nil),            // 39: urbis.StatsResponse
	(*CountRequest)(nil),             // 40: urbis.CountRequest
	(*CountResponse)(nil),            // 41: urbis.CountResponse
	(*BoundsRequest)(nil),            // 42: urbis.BoundsRequest
	(*BoundsResponse)(nil),           // 43: urbis.BoundsResponse
	(*SaveRequest)(nil),              // 44: urbis.SaveRequest
	(*SaveResponse)(nil),             // 45: urbis.SaveResponse
	(*LoadIndexRequest)(nil),         // 46: urbis.LoadIndexRequest
	(*LoadIndexResponse)(nil),        // 47: urbis.LoadIndexResponse
}
var file_urbis_proto_depIdxs = []int32{
	1,  // 0: urbis.LineString.points:type_name -> urbis.Point
	1,  // 1: urbis.Polygon.exterior:type_name -> urbis.Point
	5,  // 2: urbis.Polygon.holes:type_name -> urbis.Ring
	1,  // 3: urbis.Ring.points:type_name -> urbis.Point
	0,  // 4: urbis.SpatialObject.type:type_name -> urbis.GeomType
	1,  // 5: urbis.SpatialObject.point:type_name -> urbis.Point
	3,  // 6: urbis.SpatialObject.line:type_name -> urbis.LineString
	4,  // 7: urbis.SpatialObject.polygon:type_name -> urbis.Polygon
	1,  // 8: urbis.SpatialObject.centroid:type_name -> urbis.Point
	2,  // 9: urbis.SpatialObject.mbr:type_name -> urbis.MBR
	2,  // 10: urbis.Stats.bounds:type_name -> urbis.MBR
	7,  // 11: urbis.CreateIndexRequest.config:type_name -> urbis.Config
	1,  // 12: urbis.InsertLineStringRequest.points:type_name -> urbis.Point
	1,  // 13: urbis.InsertPolygonRequest.exterior:type_name -> urbis.Point
	6,  // 14: urbis.GetObjectResponse.object:type_name -> urbis.SpatialObject
	2,  // 15: urbis.RangeQueryRequest.range:type_name -> urbis.MBR
	6,  // 16: urbis.QueryResponse.objects:type_name -> urbis.SpatialObject
	2,  // 17: urbis.AdjacentPagesRequest.region:type_name -> urbis.MBR
	9,  // 18: urbis.AdjacentPagesResponse.pages:type_name -> urbis.PageInfo
	8,  // 19: urbis.StatsResponse.stats:type_name -> urbis.Stats
	2,  // 20: urbis.BoundsResponse.bounds:type_name -> urbis.MBR
	10, // 21: urbis.UrbisService.CreateIndex:input_type -> urbis.CreateIndexRequest
	12, // 22: urbis.UrbisService.DestroyIndex:input_type -> urbis.DestroyIndexRequest
	14, // 23: urbis.UrbisService.ListIndexes:input_type -> urbis.ListIndexesRequest
	16, // 24: urbis.UrbisService.LoadGeoJSON:input_type -> urbis.LoadGeoJSONRequest
	17, // 25: urbis.UrbisService.LoadGeoJSONString:input_type -> urbis.LoadGeoJSONStringRequest
	18, // 26: urbis.UrbisService.LoadWKT:input_type -> urbis.LoadWKTRequest
	20, // 27: urbis.UrbisService.InsertPoint:input_type -> urbis.InsertPointRequest
	21, // 28: urbis.UrbisService.InsertLineString:input_type -> urbis.InsertLineStringRequest
	22, // 29: urbis.UrbisService.InsertPolygon:input_type -> urbis.InsertPolygonRequest
	24, // 30: urbis.UrbisService.Remove:input_type -> urbis.RemoveRequest
	26, // 31: urbis.UrbisService.GetObject:input_type -> urbis.GetObjectRequest
	28, // 32: urbis.UrbisService.Build:input_type -> urbis.BuildRequest
	30, // 33: urbis.UrbisService.Optimize:input_type -> urbis.OptimizeRequest
	32, // 34: urbis.UrbisService.QueryRange:input_type -> urbis.RangeQueryRequest
	33, // 35: urbis.UrbisService.QueryPoint:input_type -> urbis.PointQueryRequest
	34, // 36: urbis.UrbisService.QueryKNN:input_type -> urbis.KNNQueryRequest
	32, // 37: urbis.UrbisService.QueryAdjacent:input_type -> urbis.RangeQueryRequest
	36, // 38: urbis.UrbisService.FindAdjacentPages:input_type -> urbis.AdjacentPagesRequest
	38, // 39: urbis.UrbisService.GetStats:input_type -> urbis.StatsRequest
	40, // 40: urbis.UrbisService.GetCount:input_type -> urbis.CountRequest
	42, // 41: urbis.UrbisService.GetBounds:input_type -> urbis.BoundsRequest
	44, // 42: urbis.UrbisService.Save:input_type -> urbis.SaveRequest
	46, // 43: urbis.UrbisService.Load:input_type -> urbis.LoadIndexRequest
	11, // 44: urbis.UrbisService.CreateIndex:output_type -> urbis.CreateIndexResponse
	13, // 45: urbis.UrbisService.DestroyIndex:output_type -> urbis.DestroyIndexResponse
	15, // 46: urbis.UrbisService.ListIndexes:output_type -> urbis.ListIndexesResponse
	19, // 47: urbis.UrbisService.LoadGeoJSON:output_type -> urbis.LoadResponse
	19, // 48: urbis.UrbisService.LoadGeoJSONString:output_type -> urbis.LoadResponse
	19, // 49: urbis.UrbisService.LoadWKT:output_type -> urbis.LoadResponse
	23, // 50: urbis.UrbisService.InsertPoint:output_type -> urbis.InsertResponse
	23, // 51: urbis.UrbisService.InsertLineString:output_type -> urbis.InsertResponse
	23, // 52: urbis.UrbisService.InsertPolygon:output_type -> urbis.InsertResponse
	25, // 53: urbis.UrbisService.Remove:output_type -> urbis.RemoveResponse
	27, // 54: urbis.UrbisService.GetObject:output_type -> urbis.GetObjectResponse
	29, // 55: urbis.UrbisService.Build:output_type -> urbis.BuildResponse
	31, // 56: urbis.UrbisService.Optimize:output_type -> urbis.OptimizeResponse
	35, // 57: urbis.UrbisService.QueryRange:output_type -> urbis.QueryResponse
	35, // 58: urbis.UrbisService.QueryPoint:output_type -> urbis.QueryResponse
	35, // 59: urbis.UrbisService.QueryKNN:output_type -> urbis.QueryResponse
	35, // 60: urbis.UrbisService.QueryAdjacent:output_type -> urbis.QueryResponse
	37, // 61: urbis.UrbisService.FindAdjacentPages:output_type -> urbis.AdjacentPagesResponse
	39, // 62: urbis.UrbisService.GetStats:output_type -> urbis.StatsResponse
	41, // 63: urbis.UrbisService.GetCount:output_type -> urbis.CountResponse
	43, // 64: urbis.UrbisService.GetBounds:output_type -> urbis.BoundsResponse
	45, // 65: urbis.UrbisService.Save:output_type -> urbis.SaveResponse
	47, // 66: urbis.UrbisService.Load:output_type -> urbis.LoadIndexResponse
	44, // [44:67] is the sub-list for method output_type
	21, // [21:44] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_urbis_proto_init() }
func file_urbis_proto_init() {
	if File_urbis_proto != nil {
		return
	}
	file_urbis_proto_msgTypes[5].OneofWrappers = []any{
		(*SpatialObject_Point)(nil),
		(*SpatialObject_Line)(nil),
		(*SpatialObject_Polygon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urbis_proto_rawDesc), len(file_urbis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urbis_proto_goTypes,
		DependencyIndexes: file_urbis_proto_depIdxs,
		EnumInfos:         file_urbis_proto_enumTypes,
		MessageInfos:      file_urbis_proto_msgTypes,
	}.Build()
	File_urbis_proto = out.File
	file_urbis_proto_goTypes = nil
	file_urbis_proto_depIdxs = nil
}
